// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxhZYcZj0b_R7Pip6sWSDoVwEYrBzYatY',
    appId: '1:1075543974221:web:1521608bf393ddc8c79704',
    messagingSenderId: '1075543974221',
    projectId: 'reminder-31a42',
    authDomain: 'reminder-31a42.firebaseapp.com',
    storageBucket: 'reminder-31a42.appspot.com',
    measurementId: 'G-TX7E9E9JCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ6t0C3QmCbYkbTmd3uO0A5TFaftBvgBE',
    appId: '1:1075543974221:android:46dca1277a1ba3bec79704',
    messagingSenderId: '1075543974221',
    projectId: 'reminder-31a42',
    storageBucket: 'reminder-31a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGyfWhMpZsNYPCJWz__8Li05SBJoL4JY',
    appId: '1:1075543974221:ios:48835c4e74bb98c1c79704',
    messagingSenderId: '1075543974221',
    projectId: 'reminder-31a42',
    storageBucket: 'reminder-31a42.appspot.com',
    iosClientId: '1075543974221-57vb8gis0rsi37pn3stpi0tkh9gvnnul.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcGyfWhMpZsNYPCJWz__8Li05SBJoL4JY',
    appId: '1:1075543974221:ios:48835c4e74bb98c1c79704',
    messagingSenderId: '1075543974221',
    projectId: 'reminder-31a42',
    storageBucket: 'reminder-31a42.appspot.com',
    iosClientId: '1075543974221-57vb8gis0rsi37pn3stpi0tkh9gvnnul.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailynotes',
  );
}
